# Save recommender


In [76]:
import pandas as pd
import os, sys
import json

import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_recommenders as tfrs
from tensorflow.keras.applications.xception import preprocess_input
from tensorflow.keras.preprocessing import image
from typing import Union, Optional, Tuple, Dict, Text

from PIL import Image
import matplotlib.pyplot as plt 
from time import time
import numpy as np

sys.path.append('../src')

import settings
import utils
from utils import make_fpath_from_id
from preprocess_images import resize_image
from utils_tf import ImageNormalizer, parse_image_func
from create_recommender import test_an_id, create_image_query_from_fpath


In [2]:
tfrs.__version__

'v0.6.0'

In [3]:
tf.__version__

'2.6.0'

# Load metadata

In [4]:
metadata_path = "../data/processed/ethz/metadata/metadata.csv"
df_meta = pd.read_csv(metadata_path, index_col='id')
df_meta

record_id                                          image_url  \
id                                                                    
1000       22890  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
1001      294531  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
1002       59785  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
1003        8041  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
1004      101503  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
...          ...                                                ...   
25284       9979  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
25285       9980  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
25286       9986  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
25287       9989  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
25288       9990  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   

      inventory_number                                             person  \
id                                                                          
1000       D 001368.34            Dürer, Albrecht (1471 - 1528), Künstler   
1001          D 027604                      Webre [?], François, Künstler   
1002          B 001012        Ammann, Hans Conrad (1634 - 1707), Künstler   
1003        D 010011.3  Carracci, Agostino (1557 - 1602); Castello, Be...   
1004         2013.0279   Ramberg, Johann Heinrich (1763 - 1840), Künstler   
...                ...                                                ...   
25284         D 013066  Speckter, Otto (1807 - 1871), Radierer; Buddeu...   
25285     D 006141.1-7  Saenredam, Jan Pietersz. (1565 um - 1607), Kün...   
25286         D 012454  Duchesne, J. M. (1751 um - um 1800 tätig); Wat...   
25287         D 000829  Beauvarlet, Jacques-Firmin (1731 - 1797); Vien...   
25288         D 012972  Raimondi, Marcantonio (1470 / 1482 um - um 152...   

                                             date  \
id                                                  
1000          Enstehung des Druckträgers: Um 1510   
1001   Enstehung des Druckträgers: Um 1700 - 1800   
1002                             Entstehung: 1645   
1003             Enstehung des Druckträgers: 1590   
1004             Enstehung des Druckträgers: 1825   
...                                           ...   
25284         Enstehung des Druckträgers: Um 1839   
25285            Enstehung des Druckträgers: 1596   
25286         Enstehung des Druckträgers: Um 1770   
25287     Enstehung des Druckträgers: 1746 - 1797   
25288     Enstehung des Druckträgers: 1504 - 1505   

                                                   title classification  \
id                                                                        
1000   Ungläubiger Thomas, Blatt 34 der Folge "Kleine...   Druckgraphik   
1001   Blatt 7 und 8 einer Folge von Darstellungen kl...   Druckgraphik   
1002                                       Reissbüchlein           Buch   
1003   Plünderungszug bringt die Waffen und die blutg...   Druckgraphik   
1004                      Ohne Titel [Paar vor Herberge]  Handzeichnung   
...                                                  ...            ...   
25284  Rückkehr von der Kindertaufe, Blatt 24 aus "Al...   Druckgraphik   
25285                              Sieben Planetengötter   Druckgraphik   
25286                                            Elefant   Druckgraphik   
25287                                     Opfer an Venus   Druckgraphik   
25288                           Christus in der Vorhölle   Druckgraphik   

                         material_technique  \
id                                            
1000                            Holzschnitt   
1001   Kupferstich, Radierung, Papier vergé   
1002     Feder, handkoloriert, Papier vergé   
1003                            Kupferstich   
1004              Aquarell, dubliert, Feder   
...                                     ...   
25284                      Radierung, V

# Test Retrieval using image and metadata features together

In [5]:
fpath_feat = "../data/processed/ethz/features/features_meta.csv"
df_feat = pd.read_csv(fpath_feat, header=0, index_col=0)
if 'index' in df_feat.columns:
    df_feat = df_feat.drop(columns='index')

In [6]:
identifiers = df_feat.index.tolist()
features = df_feat.values

In [7]:
df_feat.head()

classification_id_1  classification_id_2  classification_id_3  \
id                                                                    
1001                    0                    1                    0   
1002                    1                    0                    0   
1003                    0                    1                    0   
1004                    0                    0                    1   
1005                    0                    1                    0   

      classification_id_4  classification_id_5  material_technique_id_1  \
id                                                                        
1001                    0                    0                        0   
1002                    0                    0                        0   
1003                    0                    0                        0   
1004                    0                    0                        0   
1005                    0                    0                        0   

      material_technique_id_2  material_technique_id_3  \
id                                                       
1001                        0                        0   
1002                        0                        0   
1003                        0                        0   
1004                        0                        0   
1005                        0                        0   

      material_technique_id_4  material_technique_id_5  ...       503  \
id                                                      ...             
1001                        0                        0  ...  2.846410   
1002                        0                        0  ...  2.825450   
1003                        0                        0  ...  1.732787   
1004                        1                        0  ...  1.486095   
1005                        0                        0  ...  3.296460   

           504       505       506       507       508       509       510  \
id                                                                           
1001  0.476454  0.393871 -0.172278 -0.741765  0.044209  0.489517 -0.741765   
1002 -0.035121  0.156008 -0.014497 -0.140456  0.799459  0.425874 -0.610783   
1003  0.833400  1.733942  0.294127 -0.479517  0.290155  0.499136 -0.628738   
1004  0.436128  1.224127  0.514769  0.458842 -0.188758  0.706383 -0.716077   
1005  1.094629  1.992935  0.360293 -0.185952  1.261770  0.192709 -0.584842   

           511       512  
id                        
1001  0.296849 -0.741765  
1002  0.800544 -0.610783  
1003  0.564708 -0.628738  
1004  0.447603 -0.716077  
1005  0.739166 -0.584842  

[5 rows x 638 columns]

In [8]:
df_feat.query("classification_id_1 == 1")

classification_id_1  classification_id_2  classification_id_3  \
id                                                                     
1002                     1                    0                    0   
1288                     1                    0                    0   
1289                     1                    0                    0   
1290                     1                    0                    0   
1291                     1                    0                    0   
...                    ...                  ...                  ...   
23348                    1                    0                    0   
23349                    1                    0                    0   
23353                    1                    0                    0   
23393                    1                    0                    0   
24612                    1                    0                    0   

       classification_id_4  classification_id_5  material_technique_id_1  \
id                                                                         
1002                     0                    0                        0   
1288                     0                    0                        0   
1289                     0                    0                        0   
1290                     0                    0                        0   
1291                     0                    0                        0   
...                    ...                  ...                      ...   
23348                    0                    0                        0   
23349                    0                    0                        0   
23353                    0                    0                        0   
23393                    0                    0                        0   
24612                    0                    0                        0   

       material_technique_id_2  material_technique_id_3  \
id                                                        
1002                         0                        0   
1288                         0                        0   
1289                         0                        0   
1290                         0                        0   
1291                         0                        0   
...                        ...                      ...   
23348                        0                        0   
23349                        0                        0   
23353                        0                        0   
23393                        0                        0   
24612                        0                        0   

       material_technique_id_4  material_technique_id_5  ...       503  \
id                                                       ...             
1002                         0                        0  ...  2.825450   
1288                         0                        0  ...  3.024016   
1289                         0                        0  ...  3.188366   
1290                         0                        0  ...  2.926200   
1291                         0                        0  ...  2.202350   
...                        ...                      ...  ...       ...   
23348                        0                        0  ...  2.464424   
23349                        0                        0  ...  3.207061   
23353                        0                        0  ...  3.244109   
23393                        0                        0  ...  2.953818   
24612                        0                        0  ...  2.941550   

            504       505       506       507       508       509       510  \
id                                                                            
1002  -0.035121  0.156008 -0.014497 -0.140456  0.799459  0.425874 -0.610783   
1288   1.260875  1.005579  0.625809 -0.559870  0.817578  0.242772 -0.600122   
1289   1.551483  1.182095  0.33258

In [9]:
def load_filter_lookup():

    #replace this later with a query from the database
    types = ["MaterialTechnique", "Classification","Relationship", "Institution"]
    filter_dict = {}

    for t in types:
        fpath = f"../data/processed/ethz/fixtures/{t}.json"

        with open(fpath, 'r') as f:
            fixture = json.load(f) 

        string_lookup = {d['fields']['name']:d['pk'] for d in fixture}
        filter_dict[t] = string_lookup

    return filter_dict


def make_filter_vec(filter_dict, fltr_type, qry_names):

    qry_vec = np.zeros(len(filter_dict[fltr_type]), dtype=int)
    #subtract 1 as vector is zero indexed but database index starts at 1
    indices = [filter_dict[fltr_type].get(qry_name) -1 for qry_name in qry_names]
#     print(f"{fltr_type} indices: ",indices)

    qry_vec[indices] = 1

    return qry_vec

In [10]:
def str_qry_to_vec(filter_dict,
                   class_qry=[], 
                   mat_tec_qry=[], 
                   rel_qry=[],
                   inst_qry=[]):
    """look up several queries in one function"""

    class_vec = make_filter_vec(filter_dict,
                                fltr_type="Classification",
                                qry_names=class_qry)

    mat_tec_vec = make_filter_vec(filter_dict,
                                  fltr_type="MaterialTechnique",
                                  qry_names=mat_tec_qry)    

    rel_vec = make_filter_vec(filter_dict,
                                fltr_type="Relationship",
                                qry_names=rel_qry)
    
    inst_vec = make_filter_vec(filter_dict,
                                fltr_type="Institution",
                                qry_names=inst_qry)

    qry_vec = np.hstack([class_vec,
                     mat_tec_vec,
                     rel_vec,
                     inst_vec])

    return qry_vec

###  Testing Lookup

In [22]:
filter_dict = load_filter_lookup()

In [48]:
## manually create a vector for testing
classification_qry_names = ["Druckgraphik"]
classification_qry_vec = [1,0]
mat_tec_qry_names = ["aluminiumdruck","kupferstich","zink"]
mat_tec_qry_vec = [1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1]
relationship_qry_names = ["zustandsvariante"]
relationship_qry_vec = [0,0,0,0,1]
institution_qry_names = []
institution_qry_vec = [0,]

qry_names = [classification_qry_names,
             mat_tec_qry_names,
             relationship_qry_names,
             institution_qry_names]

qry_vec_true = np.hstack([classification_qry_vec,
                     mat_tec_qry_vec,
                     relationship_qry_vec,
                     institution_qry_vec])
qry_vec_true


array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0])

In [25]:
qry_vec_test = str_qry_to_vec(filter_dict, 
                              class_qry=classification_qry_names, 
                              mat_tec_qry=mat_tec_qry_names, 
                              rel_qry=relationship_qry_names,
                              inst_qry=institution_qry_names)
qry_vec_test

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

# Make a Brute Force Model

In [46]:
class EmbeddingMetaCross(tf.keras.Model):
    
    def __init__(self, 
                 identifiers=None,
                 candidates_embed=None,
                 candidates_meta=None,
                 query_model=None,
                 k=50):
        super().__init__()
        self.identifiers = identifiers 
        self.candidates_embed = candidates_embed 
        self.candidates_meta = candidates_meta
        self.query_model = query_model
        self.k = tf.cast(k,tf.int32)
    
    def call(self, inputs):
         
        queries_embed = inputs[0]
        
        if self.query_model is not None:
            queries_embed = self.query_model(queries_embed)

        queries_meta = inputs[1]
        
        scores_meta = tf.matmul(queries_meta, self.candidates_meta, transpose_b=True)
        scores_emb = tf.matmul(queries_embed, self.candidates_embed, transpose_b=True)
        
        # add a very small amount to scores_meta to prevent zero scores
#         scores_meta = scores_meta + .0001
        # multiply scores element-wise
        scores = tf.multiply(scores_meta, scores_emb)
        # get top results
        scores, indices = tf.math.top_k(scores, k=self.k)
    
        # look up identifiers
        identifiers = tf.gather(self.identifiers, indices)

        return scores, identifiers

In [27]:
fpath_feat = "../data/processed/ethz/features/features_meta.csv"
df_feat = pd.read_csv(fpath_feat, header=0, index_col=0)
if 'index' in df_feat.columns:
    df_feat = df_feat.drop(columns='index')

In [28]:
metadata_cols = [col for col in df_feat.columns if '_id' in col]
df_feat_meta = df_feat.loc[:,metadata_cols]

#embedding cols
embed_cols = [col for col in df_feat.columns if col not in metadata_cols]
df_feat_embed = df_feat.loc[:,embed_cols]


In [29]:
identifiers = df_feat_meta.index.tolist()
identifiers = tf.constant(identifiers, dtype=tf.int32)

candidates_meta = tf.constant(df_feat_meta.values, dtype=tf.float32)
candidates_embed = tf.constant(df_feat_embed.values, dtype=tf.float32)
k=100
k = tf.constant(k, dtype=tf.int32)
index = EmbeddingMetaCross(identifiers=identifiers, 
                      candidates_embed=candidates_embed, 
                      candidates_meta=candidates_meta, 
                      k=k)


### querying with embeddings

In [32]:
# qry_embed = tf.constant(qry_series_embed.values, dtype=tf.float32)
# qry_meta = tf.constant(qry_series_meta.values, dtype=tf.float32)
# k = tf.constant(100, dtype=tf.float32)

In [34]:
i = 3
# get image embeddings
qry_series_embed = df_feat_embed.iloc[i,:].copy()
qry_series_meta = df_feat_meta.iloc[i,:].copy()

# add text based filters
qry_classification = ["Druckgraphik",]
qry_mat_tec = ["dubliert",]

qry_meta_vec = str_qry_to_vec(filter_dict, 
               class_qry=qry_classification, 
               mat_tec_qry=qry_mat_tec, 
               rel_qry=[],
               inst_qry=[])


qry_embed = tf.constant(qry_series_embed.values, dtype=tf.float32)
qry_meta = tf.constant(qry_meta_vec, dtype=tf.float32)

# reshape query as a batch
qry_inputs = (qry_embed, qry_meta)
qry_inputs = [tf.expand_dims(x,0) for x in qry_inputs]

scores,indices = index.call(qry_inputs)
scores,indices

In [35]:
df_meta.loc[indices.numpy()[0],:]

record_id                                          image_url  \
id                                                                    
19558      31086  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
22113      34268  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
19470      30973  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
21742       3376  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
2558       14586  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
...          ...                                                ...   
5854       21528  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
22656       4706  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
14175      26044  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
21045      32845  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
18509      29978  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   

      inventory_number                                             person  \
id                                                                          
19558         D 015776  Aldegrever, Heinrich (1502 - 1555 / 1561), Kün...   
22113         D 016549  Guidi, Raffaello (1540 um - 1614), Künstler; G...   
19470         D 015828  Aldegrever, Heinrich (1502 - 1555 / 1561), Kün...   
21742         D 013092  Neeffs, Jacobus (1610 - nach 1660), Ausführung...   
2558          D 000732  Anonym (Datierung unbekannt), Künstler; Saenre...   
...                ...                                                ...   
5854          D 011374  Suyderhoff, Jonas (1613 um - 1686); Ostade, Ad...   
22656         D 013081  Vorsterman (der Ältere), Lucas (1595 - 1675), ...   
14175         D 011942  Davent, Léon (1540 - 1556 tätig); Primaticcio,...   
21045         D 016976  Muller, Jan Harmensz. (1571 - 1628), Künstler;...   
18509         D 009911  Davent, Léon (1540 - 1556 tätig); Penni, Luca ...   

                                          date  \
id                                               
19558         Enstehung des Druckträgers: 1555   
22113         Enstehung des Druckträgers: 1613   
19470         Enstehung des Druckträgers: 1555   
21742  Enstehung des Druckträgers: 1626 - 1660   
2558   Enstehung des Druckträgers: 1600 - 1634   
...                                        ...   
5854   Enstehung des Druckträgers: 1633 - 1686   
22656         Enstehung des Druckträgers: 1621   
14175  Enstehung des Druckträgers: 1540 - 1545   
21045      Enstehung des Druckträgers: Um 1591   
18509         Enstehung des Druckträgers: 1547   

                                                   title classification  \
id                                                                        
19558  Susanna des Ehebruchs angeklagt, Blatt 2 der F...   Druckgraphik   
22113                                             Merkur   Druckgraphik   
19470  Lot und die beiden Engel, Blatt 1 der Folge "D...   Druckgraphik   
21742                      Martyrium des Heiligen Thomas   Druckgraphik   
2558                        David mit dem Haupt Goliaths   Druckgraphik   
...                                                  ...            ...   
5854                      Bauernstube mit tanzendem Paar   Druckgraphik   
22656                                Anbetung der Könige   Druckgraphik   
14175                       Herkules schläft bei Omphale   Druckgraphik   
21045                     Venus, von den Nymphen verehrt   Druckgraphik   
18509                  Camillus erscheint bei den Römern   Druckgraphik   

                        material_technique  \
id                                           
19558  Papier vergé, dubliert, Kupferstich   
22113  Papier vergé, Kupferstich, dubliert   
19470  Papier vergé, Kupferstich, dubliert   
21742                Kupferstich, dubliert   
2558   Kupferstich, dubliert, Papier vergé   
...                                    ...   
5854                 Kupferstich, dubliert   
22656                dubliert, Kupfersti

In [36]:
embed_shape = tf.keras.Input(shape=(512,), dtype=tf.float32)
meta_shape = tf.keras.Input(shape=(126,), dtype=tf.float32) 
# k_shape = tf.keras.Input(shape=(1,), dtype=tf.float32)
inputs_shapes = [embed_shape, meta_shape]

In [37]:
index(inputs_shapes)
index.build(input_shape=index.input_shape)

In [38]:
index(qry_inputs)

(<tf.Tensor: shape=(1, 100), dtype=float32, numpy=
 array([[926.0102 , 922.14685, 921.5996 , 921.55566, 920.19806, 919.73914,
         919.23206, 918.7919 , 918.19116, 918.1645 , 917.4928 , 917.33203,
         917.2022 , 917.0423 , 916.9166 , 916.85126, 916.3197 , 916.22754,
         915.7867 , 914.4802 , 914.4411 , 914.14154, 913.68915, 913.0585 ,
         912.94214, 912.4873 , 911.9475 , 910.6373 , 910.50336, 910.30005,
         910.2628 , 910.078  , 909.8285 , 909.82245, 909.799  , 909.5833 ,
         909.5707 , 909.1105 , 909.02783, 908.65   , 908.05707, 907.95154,
         907.1883 , 906.90173, 906.756  , 906.36816, 905.9768 , 905.6759 ,
         905.3124 , 904.02094, 903.7554 , 903.6174 , 903.4478 , 903.1427 ,
         903.0105 , 902.94037, 902.592  , 902.4507 , 902.2732 , 902.24426,
         901.568  , 901.50165, 900.99976, 900.83234, 900.74225, 900.5747 ,
         900.4672 , 900.2453 , 899.9059 , 899.7362 , 899.70465, 899.68866,
         899.6022 , 899.4207 , 899.4023 , 899.088

### Save Model

In [39]:
tf.saved_model.save(index,"../models/retrieval/3")

INFO:tensorflow:Assets written to: ../models/retrieval/3/assets


### Reload Model
test query with reloaded model

In [40]:
index_load = tf.saved_model.load("../models/retrieval/3")

In [41]:
index_load(qry_inputs)

(<tf.Tensor: shape=(1, 100), dtype=float32, numpy=
 array([[926.0102 , 922.14685, 921.5996 , 921.55566, 920.19806, 919.73914,
         919.23206, 918.7919 , 918.19116, 918.1645 , 917.4928 , 917.33203,
         917.2022 , 917.0423 , 916.9166 , 916.85126, 916.3197 , 916.22754,
         915.7867 , 914.4802 , 914.4411 , 914.14154, 913.68915, 913.0585 ,
         912.94214, 912.4873 , 911.9475 , 910.6373 , 910.50336, 910.30005,
         910.2628 , 910.078  , 909.8285 , 909.82245, 909.799  , 909.5833 ,
         909.5707 , 909.1105 , 909.02783, 908.65   , 908.05707, 907.95154,
         907.1883 , 906.90173, 906.756  , 906.36816, 905.9768 , 905.6759 ,
         905.3124 , 904.02094, 903.7554 , 903.6174 , 903.4478 , 903.1427 ,
         903.0105 , 902.94037, 902.592  , 902.4507 , 902.2732 , 902.24426,
         901.568  , 901.50165, 900.99976, 900.83234, 900.74225, 900.5747 ,
         900.4672 , 900.2453 , 899.9059 , 899.7362 , 899.70465, 899.68866,
         899.6022 , 899.4207 , 899.4023 , 899.088

# query with image

#### make model

In [92]:
fpath_model = settings.model_fldr_path
ftx_model = tf.keras.models.load_model(fpath_model)

k=100
k = tf.constant(k, dtype=tf.int32)
index = EmbeddingMetaCross(identifiers=identifiers, 
                           candidates_embed=candidates_embed,
                           candidates_meta=candidates_meta,
                           query_model=ftx_model,
                           k=k)

#### make query

In [83]:
def preprocess_img(image_path_or_stream, DEBUG=True):

    img = Image.open(image_path_or_stream)
    img = img.convert("RGB")
    size = 224, 224
    img = resize_image(img, size[0])
    if DEBUG:
        print('np array shape: ', np.array(img).shape)
    img = img.resize(size, Image.ANTIALIAS)
    img = np.array(img)
    if DEBUG:
        print('np array shape: ', img.shape)
    img = img / 255
    img = img.tolist()

    return img


np array shape:  (224, 224, 3)
np array shape:  (224, 224, 3)


1004

In [112]:
i = 3
db_id= df_feat_embed.index[i]
# get image 
fpath = df_meta.loc[db_id,"fpath"]
img = preprocess_img(fpath)
qry_img = tf.constant([img,], dtype=tf.float32)

# add text based filters
qry_classification = ["Druckgraphik",]
qry_mat_tec = ["kupferstich"]
# convert to vector
meta_vec = str_qry_to_vec(filter_dict, 
               class_qry=qry_classification, 
               mat_tec_qry=qry_mat_tec, 
               rel_qry=[],
               inst_qry=[])
# make query tensors
qry_meta = tf.constant(meta_vec, dtype=tf.float32)
qry_img = tf.constant(img, dtype=tf.float32)

# reshape query as a batch
qry_inputs = (qry_img, qry_meta)
qry_inputs = [tf.expand_dims(x,0) for x in qry_inputs]

scores,indices = index.call(qry_inputs)
scores,indices

np array shape:  (224, 224, 3)
np array shape:  (224, 224, 3)


(<tf.Tensor: shape=(1, 100), dtype=float32, numpy=
 array([[943.42346, 942.2776 , 941.84   , 940.76086, 939.24976, 938.08344,
         937.8844 , 936.4646 , 935.5697 , 935.2591 , 935.0945 , 934.9088 ,
         934.50586, 934.0117 , 933.9233 , 933.7363 , 933.08105, 933.01483,
         932.4539 , 932.42303, 932.3636 , 932.08014, 932.06085, 931.6792 ,
         931.5777 , 931.5491 , 931.17834, 931.06964, 931.0294 , 930.8482 ,
         930.7744 , 930.6373 , 930.59985, 930.46985, 930.36035, 930.355  ,
         930.2127 , 930.0593 , 930.02026, 929.9757 , 929.78235, 929.57745,
         929.4552 , 929.40015, 929.2332 , 929.2309 , 929.2124 , 929.09375,
         929.0638 , 929.05927, 929.00366, 928.8773 , 928.7346 , 928.7013 ,
         928.66327, 928.48596, 928.3865 , 928.3609 , 928.13336, 928.03577,
         928.0036 , 927.9312 , 927.9175 , 927.8589 , 927.8469 , 927.66583,
         927.5918 , 927.52545, 927.4398 , 927.33167, 927.16925, 927.1676 ,
         927.0952 , 927.03955, 927.0237 , 927.014

In [113]:
df_meta.loc[indices.numpy()[0],:]

record_id                                          image_url  \
id                                                                    
1424        1143  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
24543       8591  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
8839      236573  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
6043       21790  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
6683       22301  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
...          ...                                                ...   
11829     247488  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
9211      236932  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
19558      31086  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
19817      31372  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   
20267      31921  https://e-gs.ethz.ch/eMP/eMuseumPlus?service=I...   

      inventory_number                                             person  \
id                                                                          
1424       D 001367.25  Raimondi, Marcantonio (1470 / 1482 um - um 152...   
24543       D 007895.4          Aldegrever, Heinrich (1502 - 1555 / 1561)   
8839          D 021880  Passe (der Ältere), Crispijn de (1564 - 1637),...   
6043          D 007686            Dürer, Albrecht (1471 - 1528), Künstler   
6683          D 012898       Wierix, Hieronymus (1553 - 1619), Kopie nach   
...                ...                                                ...   
11829         D 025264     Schoel, Hendrik van (1622 gestorben), Künstler   
9211          D 022227          Anonym (Datierung unbekannt), Künstler/in   
19558         D 015776  Aldegrever, Heinrich (1502 - 1555 / 1561), Kün...   
19817         D 016933  Saenredam, Jan Pietersz. (1565 um - 1607), Kün...   
20267         D 000720  Muller, Jan Harmensz. (1571 - 1628), Künstler;...   

                                                    date  \
id                                                         
1424             Enstehung des Druckträgers: 1510 - 1515   
24543                   Enstehung des Druckträgers: 1540   
8839          Enstehung des Druckträgers: Um 1585 - 1637   
6043                    Enstehung des Druckträgers: 1523   
6683   Enstehung des Druckträgers: Um 1700 - Um 1800 ...   
...                                                  ...   
11829         Enstehung des Druckträgers: Um 1600 - 1622   
9211   Enstehung des Druckträgers: 1550 - 1600 [zweit...   
19558                   Enstehung des Druckträgers: 1555   
19817                   Enstehung des Druckträgers: 1604   
20267         Enstehung des Druckträgers: Um 1615 - 1620   

                                                   title classification  \
id                                                                        
1424   Christus am Kreuz, Blatt 25 der Folge "Die Pas...   Druckgraphik   
24543  Adam und Eva verstecken sich vor Gott, Blatt 4...   Druckgraphik   
8839                                  Versuchung Christi   Druckgraphik   
6043                                Apostel Bartholomäus   Druckgraphik   
6683                                   Heiliger Antonius   Druckgraphik   
...                                                  ...            ...   
11829       Anbetung des Christuskindes durch die Hirten   Druckgraphik   
9211            Mann mit Zirkel und Dreieck, Architektur   Druckgraphik   
19558  Susanna des Ehebruchs angeklagt, Blatt 2 der F...   Druckgraphik   
19817  Adam und Eva bei der Arbeit, Blatt 5 der Folge...   Druckgraphik   
20267                                  Beweinung Christi   Druckgraphik   

                        material_technique  \
id                                           
1424                           Kupferstich   
24543                          Kupferstich   
8839             Kupferstich, Papier vergé   
6043                           Kupferstich   
6683                           Kupferstich   
..

# experiment with cosine similarity for post ranking

In [42]:
df_feat.iloc[:,126:].loc[indices.numpy()[0]]

1         2         3         4         5         6         7  \
id                                                                            
19558  0.114296 -0.597790  0.498638 -0.597790 -0.225226 -0.597790 -0.597790   
22113  0.597441 -0.668479  1.856117 -0.668479  0.201761 -0.668479 -0.662563   
19470  0.195953 -0.618876  1.424347 -0.493038  0.318731 -0.618876 -0.618876   
21742  0.874752 -0.665188  0.295080 -0.665188  0.283479 -0.665188 -0.519762   
2558  -0.199405 -0.635149  0.591217 -0.635149  0.474040 -0.635149 -0.635149   
...         ...       ...       ...       ...       ...       ...       ...   
5854   0.562475 -0.598707  1.151434 -0.598707 -0.154313 -0.598707 -0.526713   
22656  0.496757 -0.670724  1.181979 -0.315514  0.178492 -0.670724 -0.670724   
14175  0.411391 -0.607947  0.894980 -0.500327  0.226460 -0.607947 -0.607947   
21045  0.115656 -0.655357  0.800468 -0.385348 -0.260987 -0.655357 -0.655357   
18509  0.307804 -0.606728  1.327044 -0.606728 -0.109085 -0.606728 -0.606728   

              8         9        10  ...       503       504       505  \
id                                   ...                                 
19558  0.689815 -0.468098 -0.597790  ...  1.976307  0.451277  1.376148   
22113  1.044212  0.038411 -0.668479  ...  1.726870  0.363160  1.279065   
19470  0.350226  0.499453 -0.321029  ...  1.783194  0.272848  1.409922   
21742  0.586755 -0.649769 -0.665188  ...  1.675358  1.012375  1.636367   
2558   0.516687  0.909131 -0.635149  ...  1.999421  0.296637  1.353028   
...         ...       ...       ...  ...       ...       ...       ...   
5854   0.071257 -0.598707 -0.598707  ...  1.890669  0.223787  1.258144   
22656  0.107324  0.513196 -0.324476  ...  2.308914  0.417688  1.249788   
14175  0.222191 -0.561596 -0.607947  ...  2.297712  0.950209  1.551591   
21045  1.050161  0.757506 -0.451030  ...  1.818595  0.583553  1.351623   
18509  0.345726  0.144677 -0.417197  ...  2.776841  0.950319  1.390884   

            506       507       508       509       510       511       512  
id                                                                           
19558  0.143139 -0.223372  0.482784  1.100477 -0.597790  0.384275 -0.597790  
22113  0.413696 -0.311629  0.359807  0.568241 -0.668479  0.296696 -0.668479  
19470  0.280465  0.151470  0.447525  0.624614 -0.618876  0.299529 -0.618876  
21742  0.311924 -0.277919  0.103804 -0.017347 -0.665188  1.265564 -0.665188  
2558   0.670003 -0.059568  0.238252  0.640529 -0.635149  0.280776 -0.635149  
...         ...       ...       ...       ...       ...       ...       ...  
5854   0.669032 -0.593278 -0.038801  0.554865 -0.598707  0.638352 -0.598707  
22656  0.270655 -0.226221  0.995771  0.189609 -0.670724  0.928864 -0.670724  
14175  0.599280 -0.479417  0.531842  0.391015 -0.607947  1.028079 -0.607947  
21045  0.713923  0.746826  0.310634  0.306423 -0.655357  0.348283 -0.655357  
18509  0.661025 -0.145723  1.132786  0.855686 -0.606728  1.131087 -0.606728  

[100 rows x 512 columns]

In [244]:
cosine_loss = tf.keras.losses.CosineSimilarity(axis=-1,reduction=tf.keras.losses.Reduction.NONE)

In [245]:
cosine_loss(tf.broadcast_to(qry_embed, [100, 512]), tf.constant(df_feat.iloc[:,126:].loc[indices.numpy()[0]].values, dtype=tf.float32) )

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([-0.90591955, -0.9020876 , -0.90159225, -0.9015013 , -0.90019584,
       -0.89975315, -0.8992799 , -0.89883447, -0.89829284, -0.8982369 ,
       -0.8975458 , -0.8973627 , -0.8972641 , -0.897153  , -0.89696026,
       -0.89692825, -0.89642584, -0.8962996 , -0.89586455, -0.8945787 ,
       -0.8944926 , -0.8943026 , -0.89389795, -0.89317983, -0.89305973,
       -0.8926155 , -0.8921059 , -0.89081836, -0.8907668 , -0.89052737,
       -0.89045805, -0.89029115, -0.89007694, -0.88997185, -0.8900322 ,
       -0.8899186 , -0.8898293 , -0.8893368 , -0.889287  , -0.8888936 ,
       -0.88824284, -0.8882134 , -0.8874745 , -0.8871348 , -0.8870317 ,
       -0.8866393 , -0.8862702 , -0.8860609 , -0.88561964, -0.88437736,
       -0.88418794, -0.88399386, -0.88387716, -0.8835293 , -0.88339233,
       -0.88327765, -0.88289875, -0.88291895, -0.8826823 , -0.8826176 ,
       -0.8820214 , -0.88194597, -0.88144004, -0.88139373, -0.8811556 ,
       -0.880972